def make_code(funcdict, filename):
    (code1, code2) = make_arrays(funcdict)
    code3 = make_ufuncs(funcdict)
    code2 = indent(code2, 4)
    code3 = indent(code3, 4)
    code = ('\n\n/** Warning this file is autogenerated!!!\n\n    Please make changes to the code generator program (%s)\n**/\n\n%s\n\nstatic void\nInitOperators(PyObject *dictionary) {\n    PyObject *f;\n\n%s\n%s\n}\n' % (filename, code1, code2, code3))
    return code