def test_roundtrip(self, engine, ext, frame):
    frame = frame.copy()
    frame['A'][:5] = np.nan
    frame.to_excel(self.path, 'test1')
    frame.to_excel(self.path, 'test1', columns=['A', 'B'])
    frame.to_excel(self.path, 'test1', header=False)
    frame.to_excel(self.path, 'test1', index=False)
    frame.to_excel(self.path, 'test1')
    recons = pd.read_excel(self.path, 'test1', index_col=0)
    tm.assert_frame_equal(frame, recons)
    frame.to_excel(self.path, 'test1', index=False)
    recons = pd.read_excel(self.path, 'test1', index_col=None)
    recons.index = frame.index
    tm.assert_frame_equal(frame, recons)
    frame.to_excel(self.path, 'test1', na_rep='NA')
    recons = pd.read_excel(self.path, 'test1', index_col=0, na_values=['NA'])
    tm.assert_frame_equal(frame, recons)
    frame.to_excel(self.path, 'test1', na_rep='88')
    recons = pd.read_excel(self.path, 'test1', index_col=0, na_values=['88'])
    tm.assert_frame_equal(frame, recons)
    frame.to_excel(self.path, 'test1', na_rep='88')
    recons = pd.read_excel(self.path, 'test1', index_col=0, na_values=[88, 88.0])
    tm.assert_frame_equal(frame, recons)
    frame.to_excel(self.path, 'Sheet1')
    recons = pd.read_excel(self.path, index_col=0)
    tm.assert_frame_equal(frame, recons)
    frame.to_excel(self.path, '0')
    recons = pd.read_excel(self.path, index_col=0)
    tm.assert_frame_equal(frame, recons)
    s = frame['A']
    s.to_excel(self.path)
    recons = pd.read_excel(self.path, index_col=0)
    tm.assert_frame_equal(s.to_frame(), recons)