def __init__(self, module):
    super(AnsibleVultrServerFacts, self).__init__(module, 'vultr_server_facts')
    self.returns = {
        'APPID': dict(key='application', convert_to='int', transform=self._get_application_name),
        'FIREWALLGROUPID': dict(key='firewallgroup', convert_to='int', transform=self._get_firewallgroup_name),
        'SUBID': dict(key='id', convert_to='int'),
        'VPSPLANID': dict(key='plan', convert_to='int', transform=self._get_plan_name),
        'allowed_bandwidth_gb': dict(convert_to='int'),
        'auto_backups': dict(key='auto_backup_enabled', convert_to='bool'),
        'cost_per_month': dict(convert_to='float'),
        'current_bandwidth_gb': dict(convert_to='float'),
        'date_created': dict(),
        'default_password': dict(),
        'disk': dict(),
        'gateway_v4': dict(key='v4_gateway'),
        'internal_ip': dict(),
        'kvm_url': dict(),
        'label': dict(key='name'),
        'location': dict(key='region'),
        'main_ip': dict(key='v4_main_ip'),
        'netmask_v4': dict(key='v4_netmask'),
        'os': dict(),
        'pending_charges': dict(convert_to='float'),
        'power_status': dict(),
        'ram': dict(),
        'server_state': dict(),
        'status': dict(),
        'tag': dict(),
        'v6_main_ip': dict(),
        'v6_network': dict(),
        'v6_network_size': dict(),
        'v6_networks': dict(),
        'vcpu_count': dict(convert_to='int'),
    }