def downgrade():
    conn = op.get_bind()
    if (conn.dialect.name == 'mysql'):
        conn.execute("SET time_zone = '+00:00'")
        op.alter_column(table_name='chart', column_name='last_modified', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='dag', column_name='last_scheduler_run', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='dag', column_name='last_pickled', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='dag', column_name='last_expired', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='dag_pickle', column_name='created_dttm', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='dag_run', column_name='execution_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='dag_run', column_name='start_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='dag_run', column_name='end_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='import_error', column_name='timestamp', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='job', column_name='start_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='job', column_name='end_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='job', column_name='latest_heartbeat', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='log', column_name='dttm', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='log', column_name='execution_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='sla_miss', column_name='execution_date', type_=mysql.DATETIME(fsp=6), nullable=False)
        op.alter_column(table_name='sla_miss', column_name='timestamp', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='task_fail', column_name='execution_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='task_fail', column_name='start_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='task_fail', column_name='end_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='task_instance', column_name='execution_date', type_=mysql.DATETIME(fsp=6), nullable=False)
        op.alter_column(table_name='task_instance', column_name='start_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='task_instance', column_name='end_date', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='task_instance', column_name='queued_dttm', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='xcom', column_name='timestamp', type_=mysql.DATETIME(fsp=6))
        op.alter_column(table_name='xcom', column_name='execution_date', type_=mysql.DATETIME(fsp=6))
    else:
        if (conn.dialect.name in ('sqlite', 'mssql')):
            return
        if (conn.dialect.name == 'postgresql'):
            conn.execute('set timezone=UTC')
        op.alter_column(table_name='chart', column_name='last_modified', type_=sa.DateTime())
        op.alter_column(table_name='dag', column_name='last_scheduler_run', type_=sa.DateTime())
        op.alter_column(table_name='dag', column_name='last_pickled', type_=sa.DateTime())
        op.alter_column(table_name='dag', column_name='last_expired', type_=sa.DateTime())
        op.alter_column(table_name='dag_pickle', column_name='created_dttm', type_=sa.DateTime())
        op.alter_column(table_name='dag_run', column_name='execution_date', type_=sa.DateTime())
        op.alter_column(table_name='dag_run', column_name='start_date', type_=sa.DateTime())
        op.alter_column(table_name='dag_run', column_name='end_date', type_=sa.DateTime())
        op.alter_column(table_name='import_error', column_name='timestamp', type_=sa.DateTime())
        op.alter_column(table_name='job', column_name='start_date', type_=sa.DateTime())
        op.alter_column(table_name='job', column_name='end_date', type_=sa.DateTime())
        op.alter_column(table_name='job', column_name='latest_heartbeat', type_=sa.DateTime())
        op.alter_column(table_name='log', column_name='dttm', type_=sa.DateTime())
        op.alter_column(table_name='log', column_name='execution_date', type_=sa.DateTime())
        op.alter_column(table_name='sla_miss', column_name='execution_date', type_=sa.DateTime(), nullable=False)
        op.alter_column(table_name='sla_miss', column_name='timestamp', type_=sa.DateTime())
        op.alter_column(table_name='task_fail', column_name='execution_date', type_=sa.DateTime())
        op.alter_column(table_name='task_fail', column_name='start_date', type_=sa.DateTime())
        op.alter_column(table_name='task_fail', column_name='end_date', type_=sa.DateTime())
        op.alter_column(table_name='task_instance', column_name='execution_date', type_=sa.DateTime(), nullable=False)
        op.alter_column(table_name='task_instance', column_name='start_date', type_=sa.DateTime())
        op.alter_column(table_name='task_instance', column_name='end_date', type_=sa.DateTime())
        op.alter_column(table_name='task_instance', column_name='queued_dttm', type_=sa.DateTime())
        op.alter_column(table_name='xcom', column_name='timestamp', type_=sa.DateTime())
        op.alter_column(table_name='xcom', column_name='execution_date', type_=sa.DateTime())