def test_argsort(self):
    self._check_accum_op('argsort', check_dtype=False)
    argsorted = self.ts.argsort()
    assert issubclass(argsorted.dtype.type, np.integer)
    s = Series([Timestamp(('201301%02d' % (i + 1))) for i in range(5)])
    assert (s.dtype == 'datetime64[ns]')
    shifted = s.shift((- 1))
    assert (shifted.dtype == 'datetime64[ns]')
    assert isna(shifted[4])
    result = s.argsort()
    expected = Series(lrange(5), dtype='int64')
    assert_series_equal(result, expected)
    result = shifted.argsort()
    expected = Series((lrange(4) + [(- 1)]), dtype='int64')
    assert_series_equal(result, expected)