def do_setup():
    verify_gpl_dependency()
    write_version()
    setup(name='apache-airflow', description='Programmatically author, schedule and monitor data pipelines', license='Apache License 2.0', version=version, packages=find_packages(exclude=['tests*']), package_data={
        '': ['airflow/alembic.ini', 'airflow/git_version'],
    }, include_package_data=True, zip_safe=False, scripts=['airflow/bin/airflow'], install_requires=['alembic>=0.9, <1.0', 'bleach~=2.1.3', 'configparser>=3.5.0, <3.6.0', 'croniter>=0.3.17, <0.4', 'dill>=0.2.2, <0.3', 'flask>=0.12.4, <0.13', 'flask-appbuilder>=1.12, <2.0.0', 'flask-admin==1.4.1', 'flask-caching>=1.3.3, <1.4.0', 'flask-login>=0.3, <0.5', 'flask-swagger==0.2.13', 'flask-wtf>=0.14.2, <0.15', 'funcsigs==1.0.0', 'future>=0.16.0, <0.17', 'gitpython>=2.0.2', 'gunicorn>=19.4.0, <20.0', 'iso8601>=0.1.12', 'jinja2>=2.7.3, <2.9.0', 'lxml>=4.0.0', 'markdown>=2.5.2, <3.0', 'pandas>=0.17.1, <1.0.0', 'pendulum==1.4.4', 'psutil>=4.2.0, <6.0.0', 'pygments>=2.0.1, <3.0', 'python-daemon>=2.1.1, <2.2', 'python-dateutil>=2.3, <3', 'python-nvd3==0.15.0', 'requests>=2.5.1, <3', 'setproctitle>=1.1.8, <2', 'sqlalchemy>=1.1.15, <1.2.0', 'tabulate>=0.7.5, <=0.8.2', 'tenacity==4.8.0', 'thrift>=0.9.2', 'tzlocal>=1.4', 'unicodecsv>=0.14.1', 'werkzeug>=0.14.1, <0.15.0', 'zope.deprecation>=4.0, <5.0'], setup_requires=['docutils>=0.14, <1.0'], extras_require={
        'all': devel_all,
        'devel_ci': devel_ci,
        'all_dbs': all_dbs,
        'atlas': atlas,
        'async': async_packages,
        'azure_blob_storage': azure_blob_storage,
        'azure_data_lake': azure_data_lake,
        'cassandra': cassandra,
        'celery': celery,
        'cgroups': cgroups,
        'cloudant': cloudant,
        'crypto': crypto,
        'dask': dask,
        'databricks': databricks,
        'datadog': datadog,
        'devel': devel_minreq,
        'devel_hadoop': devel_hadoop,
        'doc': doc,
        'docker': docker,
        'druid': druid,
        'elasticsearch': elasticsearch,
        'emr': emr,
        'gcp_api': gcp_api,
        'github_enterprise': github_enterprise,
        'google_auth': google_auth,
        'hdfs': hdfs,
        'hive': hive,
        'jdbc': jdbc,
        'jira': jira,
        'kerberos': kerberos,
        'kubernetes': kubernetes,
        'ldap': ldap,
        'mongo': mongo,
        'mssql': mssql,
        'mysql': mysql,
        'oracle': oracle,
        'password': password,
        'pinot': pinot,
        'postgres': postgres,
        'qds': qds,
        'rabbitmq': rabbitmq,
        'redis': redis,
        's3': s3,
        'salesforce': salesforce,
        'samba': samba,
        'sendgrid': sendgrid,
        'segment': segment,
        'slack': slack,
        'snowflake': snowflake,
        'ssh': ssh,
        'statsd': statsd,
        'vertica': vertica,
        'webhdfs': webhdfs,
        'winrm': winrm,
    }, classifiers=['Development Status :: 5 - Production/Stable', 'Environment :: Console', 'Environment :: Web Environment', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'License :: OSI Approved :: Apache Software License', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Topic :: System :: Monitoring'], author='Apache Software Foundation', author_email='dev@airflow.incubator.apache.org', url='http://airflow.incubator.apache.org/', download_url=('https://dist.apache.org/repos/dist/release/incubator/airflow/' + version), cmdclass={
        'test': Tox,
        'extra_clean': CleanCommand,
        'compile_assets': CompileAssets,
    }, python_requires='>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*')