def test_multiple_bases(self):
    "#23956 - Tests that inheriting models doesn't move *_ptr fields into AddField operations."
    A = ModelState('app', 'A', [('a_id', models.AutoField(primary_key=True))])
    B = ModelState('app', 'B', [('b_id', models.AutoField(primary_key=True))])
    C = ModelState('app', 'C', [], bases=('app.A', 'app.B'))
    D = ModelState('app', 'D', [], bases=('app.A', 'app.B'))
    E = ModelState('app', 'E', [], bases=('app.A', 'app.B'))
    before = self.make_project_state([])
    after = self.make_project_state([A, B, C, D, E])
    autodetector = MigrationAutodetector(before, after)
    changes = autodetector._detect_changes()
    self.assertNumberMigrations(changes, 'app', 1)
    self.assertOperationTypes(changes, 'app', 0, ['CreateModel', 'CreateModel', 'CreateModel', 'CreateModel', 'CreateModel'])
    self.assertOperationAttributes(changes, 'app', 0, 0, name='A')
    self.assertOperationAttributes(changes, 'app', 0, 1, name='B')
    self.assertOperationAttributes(changes, 'app', 0, 2, name='C')
    self.assertOperationAttributes(changes, 'app', 0, 3, name='D')
    self.assertOperationAttributes(changes, 'app', 0, 4, name='E')