@tf_export('nn.conv2d_transpose', v1=[])
def conv2d_transpose_v2(input, filters, output_shape, strides, padding='SAME', data_format='NHWC', dilations=None, name=None):
    'The transpose of `conv2d`.\n\n  This operation is sometimes called "deconvolution" after [Deconvolutional\n  Networks](http://www.matthewzeiler.com/pubs/cvpr2010/cvpr2010.pdf), but is\n  actually the transpose (gradient) of `conv2d` rather than an actual\n  deconvolution.\n\n  Args:\n    input: A 4-D `Tensor` of type `float` and shape `[batch, height, width,\n      in_channels]` for `NHWC` data format or `[batch, in_channels, height,\n      width]` for `NCHW` data format.\n    filters: A 4-D `Tensor` with the same type as `value` and shape `[height,\n      width, output_channels, in_channels]`.  `filter`\'s `in_channels` dimension\n      must match that of `value`.\n    output_shape: A 1-D `Tensor` representing the output shape of the\n      deconvolution op.\n    strides: An int or list of `ints` that has length `1`, `2` or `4`.  The\n      stride of the sliding window for each dimension of `input`. If a single\n      value is given it is replicated in the `H` and `W` dimension. By default\n      the `N` and `C` dimensions are set to 0. The dimension order is determined\n      by the value of `data_format`, see below for details.\n    padding: A string, either `\'VALID\'` or `\'SAME\'`. The padding algorithm. See\n      the "returns" section of `tf.nn.convolution` for details.\n    data_format: A string. \'NHWC\' and \'NCHW\' are supported.\n    dilations: An int or list of `ints` that has length `1`, `2` or `4`,\n      defaults to 1. The dilation factor for each dimension of`input`. If a\n      single value is given it is replicated in the `H` and `W` dimension. By\n      default the `N` and `C` dimensions are set to 1. If set to k > 1, there\n      will be k-1 skipped cells between each filter element on that dimension.\n      The dimension order is determined by the value of `data_format`, see above\n      for details. Dilations in the batch and depth dimensions if a 4-d tensor\n      must be 1.\n    name: Optional name for the returned tensor.\n\n  Returns:\n    A `Tensor` with the same type as `value`.\n\n  Raises:\n    ValueError: If input/output depth does not match `filter`\'s shape, or if\n      padding is other than `\'VALID\'` or `\'SAME\'`.\n  '
    with ops.name_scope(name, 'conv2d_transpose', [input, filter, output_shape]) as name:
        if (data_format is None):
            data_format = 'NHWC'
        channel_index = (1 if data_format.startswith('NC') else 3)
        strides = _get_sequence(strides, 2, channel_index, 'strides')
        dilations = _get_sequence(dilations, 2, channel_index, 'dilations')
        return gen_nn_ops.conv2d_backprop_input(input_sizes=output_shape, filter=filters, out_backprop=input, strides=strides, padding=padding, data_format=data_format, dilations=dilations, name=name)