def test_onboarding(self):
    self.browser.get(self.path)
    self.browser.wait_until('.onboarding-container')
    self.browser.wait_until_not('.loading-indicator')
    self.browser.snapshot(name='onboarding-choose-platform')
    self.browser.click('.platform-tile.javascript-angular')
    self.browser.click('.btn-primary')
    self.browser.wait_until('.onboarding-Configure')
    self.browser.wait_until_not('.loading-indicator')
    self.browser.snapshot(name='onboarding-configure-project')
    project = Project.objects.get(organization=self.org)
    assert (project.name == 'Angular')
    assert (project.platform == 'javascript-angular')
    self.browser.click('.btn-primary')
    self.browser.wait_until_not('.loading')
    assert self.browser.element_exists('.robot')
    assert self.browser.element_exists('.btn-primary')