

def dump_markdown(path, data):
    path = os.path.join(OUTPUT_PATH, 'markdown', path)
    try:
        os.makedirs(os.path.dirname(path))
    except OSError:
        pass
    with open(path, 'w') as f:
        template = '---\n# This file is automatically generated from the API using `api-docs/generate.py`\n# Do not manually this file.\n{}\n---\n'
        contents = template.format(json.dumps(data, sort_keys=True, indent=2))
        f.write(contents)
