

@deprecated('2016-11-30', 'Please switch to tf.summary.image. Note that tf.summary.image uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.')
def image_summary(tag, tensor, max_images=3, collections=None, name=None):
    "Outputs a `Summary` protocol buffer with images.\n\n  For an explanation of why this op was deprecated, and information on how to\n  migrate, look ['here'](https://www.tensorflow.org/code/tensorflow/contrib/deprecated/__init__.py)\n\n  The summary has up to `max_images` summary values containing images. The\n  images are built from `tensor` which must be 4-D with shape `[batch_size,\n  height, width, channels]` and where `channels` can be:\n\n  *  1: `tensor` is interpreted as Grayscale.\n  *  3: `tensor` is interpreted as RGB.\n  *  4: `tensor` is interpreted as RGBA.\n\n  The images have the same number of channels as the input tensor. For float\n  input, the values are normalized one image at a time to fit in the range\n  `[0, 255]`.  `uint8` values are unchanged.  The op uses two different\n  normalization algorithms:\n\n  *  If the input values are all positive, they are rescaled so the largest one\n     is 255.\n\n  *  If any input value is negative, the values are shifted so input value 0.0\n     is at 127.  They are then rescaled so that either the smallest value is 0,\n     or the largest one is 255.\n\n  The `tag` argument is a scalar `Tensor` of type `string`.  It is used to\n  build the `tag` of the summary values:\n\n  *  If `max_images` is 1, the summary value tag is '*tag*/image'.\n  *  If `max_images` is greater than 1, the summary value tags are\n     generated sequentially as '*tag*/image/0', '*tag*/image/1', etc.\n\n  Args:\n    tag: A scalar `Tensor` of type `string`. Used to build the `tag`\n      of the summary values.\n    tensor: A 4-D `uint8` or `float32` `Tensor` of shape `[batch_size, height,\n      width, channels]` where `channels` is 1, 3, or 4.\n    max_images: Max number of batch elements to generate images for.\n    collections: Optional list of ops.GraphKeys.  The collections to add the\n      summary to.  Defaults to [ops.GraphKeys.SUMMARIES]\n    name: A name for the operation (optional).\n\n  Returns:\n    A scalar `Tensor` of type `string`. The serialized `Summary` protocol\n    buffer.\n  "
    with ops.name_scope(name, 'ImageSummary', [tag, tensor]) as scope:
        val = gen_logging_ops._image_summary(tag=tag, tensor=tensor, max_images=max_images, name=scope)
        _Collect(val, collections, [ops.GraphKeys.SUMMARIES])
    return val
