def test_sheets(self, frame, tsframe, path):
    frame = frame.copy()
    frame['A'][:5] = np.nan
    frame.to_excel(path, 'test1')
    frame.to_excel(path, 'test1', columns=['A', 'B'])
    frame.to_excel(path, 'test1', header=False)
    frame.to_excel(path, 'test1', index=False)
    writer = ExcelWriter(path)
    frame.to_excel(writer, 'test1')
    tsframe.to_excel(writer, 'test2')
    writer.save()
    reader = ExcelFile(path)
    recons = pd.read_excel(reader, 'test1', index_col=0)
    tm.assert_frame_equal(frame, recons)
    recons = pd.read_excel(reader, 'test2', index_col=0)
    tm.assert_frame_equal(tsframe, recons)
    assert (2 == len(reader.sheet_names))
    assert ('test1' == reader.sheet_names[0])
    assert ('test2' == reader.sheet_names[1])