@with_seed()
def test_ndarray_random_randint():
    a = nd.random.randint(100, 10000, shape=(LARGE_X, SMALL_Y))
    assert (a.shape == (LARGE_X, SMALL_Y))
    low_large_value = (2 ** 32)
    high_large_value = (2 ** 34)
    a = nd.random.randint(low_large_value, high_large_value)
    low = mx.nd.array([low_large_value], dtype='int64')
    high = mx.nd.array([high_large_value], dtype='int64')
    assert (a.__gt__(low) & a.__lt__(high))